# Generated by Django 3.2.16 on 2022-11-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('ability', models.CharField(max_length=256)),
                ('experience', models.PositiveSmallIntegerField()),
                ('height', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
